# GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  CarcassoneClone_config = debug
endif
ifeq ($(config),release)
  CarcassoneClone_config = release
endif

PROJECTS := CarcassoneClone

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

CarcassoneClone:
ifneq (,$(CarcassoneClone_config))
	@echo "==== Building CarcassoneClone ($(CarcassoneClone_config)) ===="
	@${MAKE} --no-print-directory -C . -f CarcassoneClone.make config=$(CarcassoneClone_config)
endif

clean:
	@${MAKE} --no-print-directory -C . -f CarcassoneClone.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   CarcassoneClone"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"